apiVersion: v1
kind: Pod
metadata:
  name: hello
  labels:
    app: hello
spec:
  securityContext:
    runAsNonRoot: true
    runAsUser: 1000
  containers:
  - name: hello
    image: avthart/hello-app:1.0.0
    ports:
      - name: web
        containerPort: 8080
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - ALL
      readOnlyRootFilesystem: true
      runAsNonRoot: true
      runAsUser: 1000
      runAsGroup: 1000
      seccompProfile:
        type: RuntimeDefault
