---
apiVersion: v1
kind: Pod
metadata:
  name: redis
spec:
  securityContext:
    runAsNonRoot: true
    runAsUser: 1000
  containers:
  - name: redis
    image: redis
    volumeMounts:
    - name: redis-storage
      mountPath: /data/redis
  volumes:
  - name: redis-storage
    emptyDir: {}