---
apiVersion: v1
kind: Pod
metadata:
  name: valkey
spec:
  containers:
    - name: valkey
      image: valkey/valkey
      volumeMounts:
        - name: valkey-storage
          mountPath: /data
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop:
            - ALL
        readOnlyRootFilesystem: true
        runAsNonRoot: true
        runAsUser: 999
        runAsGroup: 999
        seccompProfile:
          type: RuntimeDefault
  volumes:
    - name: valkey-storage
      emptyDir: {}
