apiVersion: v1
kind: Pod
metadata:
  labels:
    app: api
  name: api
spec:
  containers:
  - image: nginx
    imagePullPolicy: Always
    name: api
    ports:
    - containerPort: 80
      protocol: TCP
