apiVersion: v1
kind: Pod
metadata:
  labels:
    app: api
  name: api
spec:
  containers:
  - image: ghcr.io/stefanprodan/podinfo:6.1.6
    imagePullPolicy: Always
    name: api
    ports:
    - containerPort: 8080
      protocol: TCP
