---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: frontend
  name: frontend
spec:
  ports:
    - port: 9898
      protocol: TCP
      targetPort: 9898
  selector:
    app: frontend
  type: ClusterIP

