apiVersion: v1
kind: Pod
metadata:
  labels:
    app: frontend
  name: frontend
spec:
  securityContext:
    runAsNonRoot: true
    runAsUser: 1000
  containers:
  - image: ghcr.io/stefanprodan/podinfo:6.1.6
    imagePullPolicy: Always
    name: frontend
    ports:
    - containerPort: 8080
      protocol: TCP
