apiVersion: v1
kind: Pod
metadata:
  name: secret-2-test-pod
spec:
  volumes:
    - name: secret-volume
      secret:
        secretName: secret-2
  containers:
    - name: test-container
      image: k8s.gcr.io/busybox
      command: [ "/bin/sh", "-c", "cat /etc/secrets/config.yaml" ]
      volumeMounts:
        - name: secret-volume
          readOnly: true
          mountPath: "/etc/secrets"
  restartPolicy: Never
