apiVersion: v1
kind: Pod
metadata:
  name: secret-2-test-pod
spec:
  volumes:
    - name: secret-volume
      secret:
        secretName: secret-2
  securityContext:
    runAsNonRoot: true
    runAsUser: 1000
  containers:
    - name: test-container
      image: k8s.gcr.io/busybox
      command: [ "/bin/sh", "-c", "cat /etc/secrets/config.yaml" ]
      volumeMounts:
        - name: secret-volume
          readOnly: true
          mountPath: "/etc/secrets"
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop:
            - ALL
        readOnlyRootFilesystem: true
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        seccompProfile:
          type: RuntimeDefault
  restartPolicy: Never
