apiVersion: v1
kind: Pod
metadata:
  name: secret-1-test-pod
spec:
  containers:
    - name: test-container
      image: k8s.gcr.io/busybox
      command: [ "/bin/sh", "-c", "env" ]
      envFrom:
      - secretRef:
          name: secret-1
  restartPolicy: Never