apiVersion: v1
kind: Pod
metadata:
  name: pod-env-cm
spec:
  containers:
    - name: test-container
      image: k8s.gcr.io/busybox
      command: [ "/bin/sh", "-c", "env" ]
      env:
        # Define the environment variable
        - name: KUBERNETES_TRAINING
          valueFrom:
            configMapKeyRef:
              # The ConfigMap containing the value you want to assign to KUBERNETES_TRAINING
              name: kubernetes-config
              # Specify the key associated with the value
              key: kubernetes.training
  restartPolicy: Never