apiVersion: v1
kind: Pod
metadata:
  name: loadgenerator
spec:
  securityContext:
    runAsNonRoot: true
    runAsUser: 1000
  containers:
  - name: loadgenerator
    image: busybox
    command:
      - sleep
      - "3600"
    imagePullPolicy: IfNotPresent
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - ALL
      readOnlyRootFilesystem: true
      runAsNonRoot: true
      runAsUser: 1000
      runAsGroup: 1000
      seccompProfile:
        type: RuntimeDefault
  restartPolicy: Always
