---
apiVersion: v1
kind: Pod
metadata:
  name: loadgenerator
  labels:
    app: loadgenerator
spec:
  securityContext:
    runAsNonRoot: true
    runAsUser: 1000
  containers:
    - name: loadgenerator
      image: busybox
      command:
        - sleep
        - "3600"
      imagePullPolicy: IfNotPresent
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop:
            - ALL
        readOnlyRootFilesystem: true
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        seccompProfile:
          type: RuntimeDefault
  restartPolicy: Always
---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: allow-egress-loadgenerator-to-frontend
spec:
  endpointSelector:
    matchLabels:
      app: loadgenerator
  egress:
  - toEndpoints:
      - matchLabels:
          app: frontend
---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: allow-ingress-frontend-from-loadgenerator
spec:
  endpointSelector:
    matchLabels:
      app: frontend
  ingress:
  - fromEndpoints:
      - matchLabels:
          app: loadgenerator
