---
replicaCount: 1
logLevel: debug
ui:
  message: "Hello <YOUR_NAME>"

serviceMonitor:
  enabled: false

securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 1000
  runAsGroup: 1000
  seccompProfile:
    type: RuntimeDefault

httpRoute:
  enabled: true
  parentRefs:
    - name: gateway
      namespace: guida-gateway-training
      sectionName: http
  hostnames:
    - <YOUR_NAME>.<YOUR_DOMAIN>
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
