replicaCount: 1
logLevel: debug
ui:
  message: "Hello <YOUR_NAME>"

serviceMonitor:
  enabled: true

ingress:
  enabled: true
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
    kubernetes.io/ingress.class: nginx
  hosts:
    - host: <YOUR_NAME>.staging.nhbdemo.nl
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
   - secretName: podinfo-tls
     hosts:
       - <YOUR_NAME>.staging.nhbdemo.nl
