replicaCount: 1
logLevel: debug
ui:
  message: "Hello <YOUR_NAME>"

serviceMonitor:
  enabled: false

ingress:
  enabled: true
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
    kubernetes.io/ingress.class: nginx
  hosts:
    - host: <YOUR_NAME>.<YOUR_DOMAIN>
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
   - secretName: podinfo-tls
     hosts:
       - <YOUR_NAME>.<YOUR_DOMAIN>
