apiVersion: v1
kind: Pod
metadata:
  name: hello-labels
  labels:
    env: development
spec:
  securityContext:
    runAsNonRoot: true
    runAsUser: 1000
  containers:
  - image: avthart/hello-app:2.0.1
    name: hello-world
    ports:
    - name: web
      containerPort: 8080
  restartPolicy: Never